### ISSUE TITLE
Building fails on Windows

### ISSUE THREAD

**Issue by loociano** [fogleman/PirateMap#5]
```
pip install -r requirements.txt

Collecting Shapely==1.5.13 (from -r requirements.txt (line 1))
  Using cached Shapely-1.5.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<redacted>\AppData\Local\Temp\pip-build-1s6hmccw\Shapely\setup.py", line 38, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "<redacted>\appdata\local\temp\pip-build-1s6hmccw\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos.dll")
      File "c:\python352\lib\ctypes\__init__.py", line 347, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in <redacted>\AppData\Local\Temp\pip-build-1s6hmccw\Shapely\
```

**Comment by loociano** [comment]
I installed GEOS from http://trac.osgeo.org/osgeo4w/, I'm getting the same error.

**Comment by fogleman** [comment]
Try the Windows installer for Shapely?

https://gis.stackexchange.com/questions/62925/why-is-shapely-not-installing-correctly
